### ISSUE TITLE
Alternative install steps

### ISSUE THREAD

**Issue by pogzie** [some-things/dkp-mirror#1]
1.) Download and install latest stable from https://nodejs.org/en/
2.) `git clone https://github.com/some-things/dkp-mirror` 
3.) `cd dkp-mirror`
4.) `chmod +x bin/cli.js` 
5.) `npm install`
6.) `dkp-mirror --help`

**Comment by some-things** [comment]
Thanks for the suggestion! I think now that we have a single binary, we can switch to using that method now versus using `npm`. If the binary ends up being problematic, I'll certainly come back to this option.
